version: '2'
services:
  web:
    image: local/as-web
    build: server
    environment:
      - PORT=5050
    env_file:
      - ./.prod/kafka.env
      - ./.prod/db.env
    ports:
      - "5050:5050"
  cache:
    image: local/as-varnish
    build: varnish
    links:
      - web:web
    depends_on:
      - web
    environment:
      - BACKEND_HOST_A=web
      - BACKEND_PORT=5050
      - BACKEND_CACHE_TIME=20m
      - BACKEND_CACHE_SIZE=64m
    ports:
      - "6081:6081"
      - "6082:6082"
  haproxy:
    image: local/as-haproxy
    build: haproxy
    links:
      - cache:cache
      - images:images
    depends_on:
      - cache
      - images
    ports:
      - "80:80"
      - "443:443"
    environment:
      - BACKEND_HOST_A=cache
      - BACKEND_PORT=6081
      - IMAGE_CACHE_HOST=images
      - IMAGE_CACHE_PORT=6060
    env_file:
      - ./.prod/ssl.env
      - ./.prod/stats.env
  images:
    image: local/as-images
    build: images
    ports:
      - "6060:6060"
    environment:
      - CACHE_DIR=/srv/imageproxy
      - PORT=6060
