version: '2'
services:
  web:
    image: maxbr/as-web:latest
    size: s1
    environment:
      - PORT=5050
    env_file:
      - ./.prod/kafka.env
      - ./.prod/db.env
  cache:
    image: maxbr/as-varnish:latest
    size: s3
    links:
      - web:web
    depends_on:
      - web
    environment:
      - BACKEND_HOST_A=web
      - BACKEND_PORT=5050
      - BACKEND_CACHE_TIME=20m
      - BACKEND_CACHE_SIZE=64m
  haproxy:
    image: maxbr/as-haproxy:latest
    fip: 209.177.88.182
    size: s2
    links:
      - cache:cache
      - images:images
    depends_on:
      - cache
      - images
    ports:
      - "80:80"
      - "443:443"
    environment:
      - BACKEND_HOST_A=cache
      - BACKEND_PORT=6081
      - IMAGE_CACHE_HOST=images
      - IMAGE_CACHE_PORT=6060
    env_file:
      - ./.prod/ssl.env
      - ./.prod/stats.env
  images:
    image: maxbr/as-images:latest
    environment:
      - CACHE_DIR=/srv/imageproxy
      - PORT=6060